# Generated by Django 4.0.1 on 2022-01-09 16:20

from django.db import migrations


def create_banks(apps, schema_editor):
    Bank = apps.get_model('banks', 'Bank')
    Bank(name='Millennium',
         country='PL').save()
    Bank(name='MBank',
         country='PL').save()
    Bank(name='ING',
         country='PL').save()


class Migration(migrations.Migration):
    dependencies = [
        ('banks', '0002_bank_country'),
    ]

    operations = [
        migrations.RunPython(create_banks)
    ]
