# Generated by Django 4.0.1 on 2022-01-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(default=dict)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='banks.bank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
