# Generated by Django 4.0.1 on 2022-01-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_alter_banktransactionimportconfig_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionimportconfig',
            name='bank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='banks.bank'),
        ),
    ]
