# Generated by Django 4.0.1 on 2022-01-10 20:28

from django.db import migrations

MILLENIUM_CONFIG = {
    "delimiter": ",",
    "newline": "",
    "start_row": 1,
    "fields": {
        "bank_account": 0,
        "transaction_date": 1,
        "description": 6,
        "expense": 7,
        "income": 8,
        "currency": 10
    }
}


def create_millenium_config(apps, schema_editor):
    Bank = apps.get_model('banks', 'Bank')
    BankTransactionImportConfig = apps.get_model('banks', 'BankTransactionImportConfig')
    millennium = Bank.objects.get(name='Millennium', country='PL')
    BankTransactionImportConfig(bank=millennium,
                                config=MILLENIUM_CONFIG).save()


class Migration(migrations.Migration):
    dependencies = [
        ('banks', '0007_alter_banktransactionimportconfig_bank'),
    ]

    operations = [
        migrations.RunPython(create_millenium_config)
    ]
